services:
  postgres:
    image: postgres:16
    env_file: .env
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  app:
    build: .
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports: ["3000:3000"]
    depends_on: [postgres]

volumes:
  postgres_data:
